# Generated by Django 4.0.4 on 2022-04-25 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('storenum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('finaceid', models.AutoField(primary_key=True, serialize=False)),
                ('fnum', models.IntegerField(default=0)),
                ('ftime', models.DateTimeField(default=django.utils.timezone.now)),
                ('fstate', models.CharField(max_length=20)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.book')),
            ],
        ),
        migrations.CreateModel(
            name='incomebooks',
            fields=[
                ('incomeid', models.AutoField(primary_key=True, serialize=False)),
                ('inprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('innum', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=20)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.book')),
            ],
        ),
        migrations.CreateModel(
            name='nor_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('ID', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '普通管理员',
            },
        ),
        migrations.CreateModel(
            name='possession',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=40)),
                ('wealth', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=40)),
                ('storephone', models.CharField(max_length=20)),
                ('storeaddress', models.CharField(max_length=40)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.possession')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('wareid', models.AutoField(primary_key=True, serialize=False)),
                ('warephone', models.CharField(max_length=20)),
                ('wareaddress', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='warestorage',
            fields=[
                ('wstoreid', models.AutoField(primary_key=True, serialize=False)),
                ('storenum', models.IntegerField(default=0)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.book')),
                ('wareid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
