# Generated by Django 4.0.4 on 2022-04-29 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startlib', '0002_book_finance_incomebooks_nor_admin_possession_store_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nor_admin',
            options={'verbose_name': 'nor_admin'},
        ),
        migrations.RemoveField(
            model_name='nor_admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='nor_admin',
            name='username',
        ),
        migrations.AddField(
            model_name='incomebooks',
            name='storeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.store'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='wealth',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('saleid', models.AutoField(primary_key=True, serialize=False)),
                ('salenum', models.IntegerField(default=0)),
                ('saletime', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.CharField(max_length=40)),
                ('saleprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.book')),
                ('storeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.store')),
            ],
        ),
        migrations.CreateModel(
            name='outcome',
            fields=[
                ('outid', models.AutoField(primary_key=True, serialize=False)),
                ('outcometime', models.DateTimeField(default=django.utils.timezone.now)),
                ('outsummoney', models.DecimalField(decimal_places=2, max_digits=13)),
                ('incomeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.incomebooks')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.possession')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('inid', models.AutoField(primary_key=True, serialize=False)),
                ('incometime', models.DateTimeField(default=django.utils.timezone.now)),
                ('insummoney', models.DecimalField(decimal_places=2, max_digits=13)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.possession')),
                ('saleid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.sale')),
                ('storeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startlib.store')),
            ],
        ),
    ]
